package com.hht.mapper;

import com.hht.models.BPayType;

import java.util.List;

public interface BPayTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_pay_type
     *
     * @mbggenerated Tue Nov 29 14:06:26 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_pay_type
     *
     * @mbggenerated Tue Nov 29 14:06:26 CST 2016
     */
    int insert(BPayType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_pay_type
     *
     * @mbggenerated Tue Nov 29 14:06:26 CST 2016
     */
    int insertSelective(BPayType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_pay_type
     *
     * @mbggenerated Tue Nov 29 14:06:26 CST 2016
     */
    BPayType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_pay_type
     *
     * @mbggenerated Tue Nov 29 14:06:26 CST 2016
     */
    int updateByPrimaryKeySelective(BPayType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_pay_type
     *
     * @mbggenerated Tue Nov 29 14:06:26 CST 2016
     */
    int updateByPrimaryKey(BPayType record);

    /**
     * 根据支付名称，查询支付方式（如果为空，查询全部）
     *
     * @param payName
     * @return
     */
    List<BPayType> selectPayList(String payName);
}