package com.hht.mapper;

import com.hht.models.BTableDynamic;

import java.util.Map;

public interface BTableDynamicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_table_dynamic
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_table_dynamic
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    int insert(BTableDynamic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_table_dynamic
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    int insertSelective(BTableDynamic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_table_dynamic
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    BTableDynamic selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_table_dynamic
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    int updateByPrimaryKeySelective(BTableDynamic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_table_dynamic
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    int updateByPrimaryKey(BTableDynamic record);

    /**
     * 根据桌号，查询动态表中是否有该桌台号
     *
     * @param map
     * @return
     */
    BTableDynamic selectByTableCode(Map<String,Object> map);
}