package com.hht.mapper;

import com.hht.models.YDishList;

public interface YDishListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_dish_list
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_dish_list
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    int insert(YDishList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_dish_list
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    int insertSelective(YDishList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_dish_list
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    YDishList selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_dish_list
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    int updateByPrimaryKeySelective(YDishList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_dish_list
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    int updateByPrimaryKey(YDishList record);
}