package com.hht.mapper;

import com.hht.models.YTableOprrecord;

public interface YTableOprrecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_table_oprrecord
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_table_oprrecord
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    int insert(YTableOprrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_table_oprrecord
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    int insertSelective(YTableOprrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_table_oprrecord
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    YTableOprrecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_table_oprrecord
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    int updateByPrimaryKeySelective(YTableOprrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_table_oprrecord
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    int updateByPrimaryKey(YTableOprrecord record);
}