package com.hht.models;

import java.util.Date;

public class BPayType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_pay_type.id
     *
     * @mbggenerated Tue Nov 29 14:06:26 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_pay_type.pay_code
     *
     * @mbggenerated Tue Nov 29 14:06:26 CST 2016
     */
    private String payCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_pay_type.pay_name
     *
     * @mbggenerated Tue Nov 29 14:06:26 CST 2016
     */
    private String payName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_pay_type.status
     *
     * @mbggenerated Tue Nov 29 14:06:26 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_pay_type.create_time
     *
     * @mbggenerated Tue Nov 29 14:06:26 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_pay_type.id
     *
     * @return the value of b_pay_type.id
     *
     * @mbggenerated Tue Nov 29 14:06:26 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_pay_type.id
     *
     * @param id the value for b_pay_type.id
     *
     * @mbggenerated Tue Nov 29 14:06:26 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_pay_type.pay_code
     *
     * @return the value of b_pay_type.pay_code
     *
     * @mbggenerated Tue Nov 29 14:06:26 CST 2016
     */
    public String getPayCode() {
        return payCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_pay_type.pay_code
     *
     * @param payCode the value for b_pay_type.pay_code
     *
     * @mbggenerated Tue Nov 29 14:06:26 CST 2016
     */
    public void setPayCode(String payCode) {
        this.payCode = payCode == null ? null : payCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_pay_type.pay_name
     *
     * @return the value of b_pay_type.pay_name
     *
     * @mbggenerated Tue Nov 29 14:06:26 CST 2016
     */
    public String getPayName() {
        return payName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_pay_type.pay_name
     *
     * @param payName the value for b_pay_type.pay_name
     *
     * @mbggenerated Tue Nov 29 14:06:26 CST 2016
     */
    public void setPayName(String payName) {
        this.payName = payName == null ? null : payName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_pay_type.status
     *
     * @return the value of b_pay_type.status
     *
     * @mbggenerated Tue Nov 29 14:06:26 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_pay_type.status
     *
     * @param status the value for b_pay_type.status
     *
     * @mbggenerated Tue Nov 29 14:06:26 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_pay_type.create_time
     *
     * @return the value of b_pay_type.create_time
     *
     * @mbggenerated Tue Nov 29 14:06:26 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_pay_type.create_time
     *
     * @param createTime the value for b_pay_type.create_time
     *
     * @mbggenerated Tue Nov 29 14:06:26 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}