package com.hht.models;

import java.util.Date;

public class BTableDynamic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_table_dynamic.id
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_table_dynamic.table_code
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    private String tableCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_table_dynamic.table_name
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_table_dynamic.table_status
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    private Integer tableStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_table_dynamic.no_disturb
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    private Integer noDisturb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_table_dynamic.dinner_type
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    private Integer dinnerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_table_dynamic.customer_id
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    private String customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_table_dynamic.order_id
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_table_dynamic.pre_order_id
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    private String preOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_table_dynamic.queue_num
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    private String queueNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_table_dynamic.person_num
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    private Integer personNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_table_dynamic.open_time
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    private Date openTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_table_dynamic.order_time
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    private Date orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_table_dynamic.dish_list_code
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    private String dishListCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_table_dynamic.offer_time
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    private Date offerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_table_dynamic.comfire_bill_time
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    private Date comfireBillTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_table_dynamic.bill_time
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    private Date billTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_table_dynamic.bill_no
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    private String billNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_table_dynamic.clear_time
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    private Date clearTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_table_dynamic.table_message
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    private String tableMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_table_dynamic.bill_close
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    private Integer billClose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_table_dynamic.table_tyoe
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    private Integer tableTyoe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_table_dynamic.id
     *
     * @return the value of b_table_dynamic.id
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_table_dynamic.id
     *
     * @param id the value for b_table_dynamic.id
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_table_dynamic.table_code
     *
     * @return the value of b_table_dynamic.table_code
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public String getTableCode() {
        return tableCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_table_dynamic.table_code
     *
     * @param tableCode the value for b_table_dynamic.table_code
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public void setTableCode(String tableCode) {
        this.tableCode = tableCode == null ? null : tableCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_table_dynamic.table_name
     *
     * @return the value of b_table_dynamic.table_name
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_table_dynamic.table_name
     *
     * @param tableName the value for b_table_dynamic.table_name
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_table_dynamic.table_status
     *
     * @return the value of b_table_dynamic.table_status
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public Integer getTableStatus() {
        return tableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_table_dynamic.table_status
     *
     * @param tableStatus the value for b_table_dynamic.table_status
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public void setTableStatus(Integer tableStatus) {
        this.tableStatus = tableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_table_dynamic.no_disturb
     *
     * @return the value of b_table_dynamic.no_disturb
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public Integer getNoDisturb() {
        return noDisturb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_table_dynamic.no_disturb
     *
     * @param noDisturb the value for b_table_dynamic.no_disturb
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public void setNoDisturb(Integer noDisturb) {
        this.noDisturb = noDisturb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_table_dynamic.dinner_type
     *
     * @return the value of b_table_dynamic.dinner_type
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public Integer getDinnerType() {
        return dinnerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_table_dynamic.dinner_type
     *
     * @param dinnerType the value for b_table_dynamic.dinner_type
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public void setDinnerType(Integer dinnerType) {
        this.dinnerType = dinnerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_table_dynamic.customer_id
     *
     * @return the value of b_table_dynamic.customer_id
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_table_dynamic.customer_id
     *
     * @param customerId the value for b_table_dynamic.customer_id
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_table_dynamic.order_id
     *
     * @return the value of b_table_dynamic.order_id
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_table_dynamic.order_id
     *
     * @param orderId the value for b_table_dynamic.order_id
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_table_dynamic.pre_order_id
     *
     * @return the value of b_table_dynamic.pre_order_id
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public String getPreOrderId() {
        return preOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_table_dynamic.pre_order_id
     *
     * @param preOrderId the value for b_table_dynamic.pre_order_id
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public void setPreOrderId(String preOrderId) {
        this.preOrderId = preOrderId == null ? null : preOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_table_dynamic.queue_num
     *
     * @return the value of b_table_dynamic.queue_num
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public String getQueueNum() {
        return queueNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_table_dynamic.queue_num
     *
     * @param queueNum the value for b_table_dynamic.queue_num
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public void setQueueNum(String queueNum) {
        this.queueNum = queueNum == null ? null : queueNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_table_dynamic.person_num
     *
     * @return the value of b_table_dynamic.person_num
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public Integer getPersonNum() {
        return personNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_table_dynamic.person_num
     *
     * @param personNum the value for b_table_dynamic.person_num
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public void setPersonNum(Integer personNum) {
        this.personNum = personNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_table_dynamic.open_time
     *
     * @return the value of b_table_dynamic.open_time
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public Date getOpenTime() {
        return openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_table_dynamic.open_time
     *
     * @param openTime the value for b_table_dynamic.open_time
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public void setOpenTime(Date openTime) {
        this.openTime = openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_table_dynamic.order_time
     *
     * @return the value of b_table_dynamic.order_time
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_table_dynamic.order_time
     *
     * @param orderTime the value for b_table_dynamic.order_time
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_table_dynamic.dish_list_code
     *
     * @return the value of b_table_dynamic.dish_list_code
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public String getDishListCode() {
        return dishListCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_table_dynamic.dish_list_code
     *
     * @param dishListCode the value for b_table_dynamic.dish_list_code
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public void setDishListCode(String dishListCode) {
        this.dishListCode = dishListCode == null ? null : dishListCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_table_dynamic.offer_time
     *
     * @return the value of b_table_dynamic.offer_time
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public Date getOfferTime() {
        return offerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_table_dynamic.offer_time
     *
     * @param offerTime the value for b_table_dynamic.offer_time
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public void setOfferTime(Date offerTime) {
        this.offerTime = offerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_table_dynamic.comfire_bill_time
     *
     * @return the value of b_table_dynamic.comfire_bill_time
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public Date getComfireBillTime() {
        return comfireBillTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_table_dynamic.comfire_bill_time
     *
     * @param comfireBillTime the value for b_table_dynamic.comfire_bill_time
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public void setComfireBillTime(Date comfireBillTime) {
        this.comfireBillTime = comfireBillTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_table_dynamic.bill_time
     *
     * @return the value of b_table_dynamic.bill_time
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public Date getBillTime() {
        return billTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_table_dynamic.bill_time
     *
     * @param billTime the value for b_table_dynamic.bill_time
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public void setBillTime(Date billTime) {
        this.billTime = billTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_table_dynamic.bill_no
     *
     * @return the value of b_table_dynamic.bill_no
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public String getBillNo() {
        return billNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_table_dynamic.bill_no
     *
     * @param billNo the value for b_table_dynamic.bill_no
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public void setBillNo(String billNo) {
        this.billNo = billNo == null ? null : billNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_table_dynamic.clear_time
     *
     * @return the value of b_table_dynamic.clear_time
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public Date getClearTime() {
        return clearTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_table_dynamic.clear_time
     *
     * @param clearTime the value for b_table_dynamic.clear_time
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public void setClearTime(Date clearTime) {
        this.clearTime = clearTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_table_dynamic.table_message
     *
     * @return the value of b_table_dynamic.table_message
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public String getTableMessage() {
        return tableMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_table_dynamic.table_message
     *
     * @param tableMessage the value for b_table_dynamic.table_message
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public void setTableMessage(String tableMessage) {
        this.tableMessage = tableMessage == null ? null : tableMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_table_dynamic.bill_close
     *
     * @return the value of b_table_dynamic.bill_close
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public Integer getBillClose() {
        return billClose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_table_dynamic.bill_close
     *
     * @param billClose the value for b_table_dynamic.bill_close
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public void setBillClose(Integer billClose) {
        this.billClose = billClose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_table_dynamic.table_tyoe
     *
     * @return the value of b_table_dynamic.table_tyoe
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public Integer getTableTyoe() {
        return tableTyoe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_table_dynamic.table_tyoe
     *
     * @param tableTyoe the value for b_table_dynamic.table_tyoe
     *
     * @mbggenerated Thu Nov 17 15:48:53 CST 2016
     */
    public void setTableTyoe(Integer tableTyoe) {
        this.tableTyoe = tableTyoe;
    }
}