package com.hht.models;

import java.math.BigDecimal;
import java.util.Date;

public class YDishListDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_dish_list_detail.id
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_dish_list_detail.dish_list_code
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    private String dishListCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_dish_list_detail.dish_code
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    private String dishCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_dish_list_detail.batch_no
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    private Integer batchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_dish_list_detail.name
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_dish_list_detail.price
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_dish_list_detail.unit
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_dish_list_detail.quantity
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    private Float quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_dish_list_detail.actual_price
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    private BigDecimal actualPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_dish_list_detail.dish_status
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    private Integer dishStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_dish_list_detail.dish_detalled_status
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    private Integer dishDetalledStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_dish_list_detail.cooking
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    private String cooking;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_dish_list_detail.remark
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_dish_list_detail.order_time
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    private Date orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_dish_list_detail.oper_type
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    private String operType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_dish_list_detail.operator
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_dish_list_detail.served_quantity
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    private Float servedQuantity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_dish_list_detail.id
     *
     * @return the value of y_dish_list_detail.id
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_dish_list_detail.id
     *
     * @param id the value for y_dish_list_detail.id
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_dish_list_detail.dish_list_code
     *
     * @return the value of y_dish_list_detail.dish_list_code
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public String getDishListCode() {
        return dishListCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_dish_list_detail.dish_list_code
     *
     * @param dishListCode the value for y_dish_list_detail.dish_list_code
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public void setDishListCode(String dishListCode) {
        this.dishListCode = dishListCode == null ? null : dishListCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_dish_list_detail.dish_code
     *
     * @return the value of y_dish_list_detail.dish_code
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public String getDishCode() {
        return dishCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_dish_list_detail.dish_code
     *
     * @param dishCode the value for y_dish_list_detail.dish_code
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public void setDishCode(String dishCode) {
        this.dishCode = dishCode == null ? null : dishCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_dish_list_detail.batch_no
     *
     * @return the value of y_dish_list_detail.batch_no
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public Integer getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_dish_list_detail.batch_no
     *
     * @param batchNo the value for y_dish_list_detail.batch_no
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public void setBatchNo(Integer batchNo) {
        this.batchNo = batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_dish_list_detail.name
     *
     * @return the value of y_dish_list_detail.name
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_dish_list_detail.name
     *
     * @param name the value for y_dish_list_detail.name
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_dish_list_detail.price
     *
     * @return the value of y_dish_list_detail.price
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_dish_list_detail.price
     *
     * @param price the value for y_dish_list_detail.price
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_dish_list_detail.unit
     *
     * @return the value of y_dish_list_detail.unit
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_dish_list_detail.unit
     *
     * @param unit the value for y_dish_list_detail.unit
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_dish_list_detail.quantity
     *
     * @return the value of y_dish_list_detail.quantity
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public Float getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_dish_list_detail.quantity
     *
     * @param quantity the value for y_dish_list_detail.quantity
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public void setQuantity(Float quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_dish_list_detail.actual_price
     *
     * @return the value of y_dish_list_detail.actual_price
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public BigDecimal getActualPrice() {
        return actualPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_dish_list_detail.actual_price
     *
     * @param actualPrice the value for y_dish_list_detail.actual_price
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public void setActualPrice(BigDecimal actualPrice) {
        this.actualPrice = actualPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_dish_list_detail.dish_status
     *
     * @return the value of y_dish_list_detail.dish_status
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public Integer getDishStatus() {
        return dishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_dish_list_detail.dish_status
     *
     * @param dishStatus the value for y_dish_list_detail.dish_status
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public void setDishStatus(Integer dishStatus) {
        this.dishStatus = dishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_dish_list_detail.dish_detalled_status
     *
     * @return the value of y_dish_list_detail.dish_detalled_status
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public Integer getDishDetalledStatus() {
        return dishDetalledStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_dish_list_detail.dish_detalled_status
     *
     * @param dishDetalledStatus the value for y_dish_list_detail.dish_detalled_status
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public void setDishDetalledStatus(Integer dishDetalledStatus) {
        this.dishDetalledStatus = dishDetalledStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_dish_list_detail.cooking
     *
     * @return the value of y_dish_list_detail.cooking
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public String getCooking() {
        return cooking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_dish_list_detail.cooking
     *
     * @param cooking the value for y_dish_list_detail.cooking
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public void setCooking(String cooking) {
        this.cooking = cooking == null ? null : cooking.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_dish_list_detail.remark
     *
     * @return the value of y_dish_list_detail.remark
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_dish_list_detail.remark
     *
     * @param remark the value for y_dish_list_detail.remark
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_dish_list_detail.order_time
     *
     * @return the value of y_dish_list_detail.order_time
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_dish_list_detail.order_time
     *
     * @param orderTime the value for y_dish_list_detail.order_time
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_dish_list_detail.oper_type
     *
     * @return the value of y_dish_list_detail.oper_type
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public String getOperType() {
        return operType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_dish_list_detail.oper_type
     *
     * @param operType the value for y_dish_list_detail.oper_type
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public void setOperType(String operType) {
        this.operType = operType == null ? null : operType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_dish_list_detail.operator
     *
     * @return the value of y_dish_list_detail.operator
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_dish_list_detail.operator
     *
     * @param operator the value for y_dish_list_detail.operator
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_dish_list_detail.served_quantity
     *
     * @return the value of y_dish_list_detail.served_quantity
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public Float getServedQuantity() {
        return servedQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_dish_list_detail.served_quantity
     *
     * @param servedQuantity the value for y_dish_list_detail.served_quantity
     *
     * @mbggenerated Thu Nov 17 16:47:00 CST 2016
     */
    public void setServedQuantity(Float servedQuantity) {
        this.servedQuantity = servedQuantity;
    }
}