package com.hht.models;

import java.util.Date;

public class YDishList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_dish_list.id
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_dish_list.bill_remark
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    private String billRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_dish_list.create_time
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_dish_list.dish_list_code
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    private String dishListCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_dish_list.id
     *
     * @return the value of y_dish_list.id
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_dish_list.id
     *
     * @param id the value for y_dish_list.id
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_dish_list.bill_remark
     *
     * @return the value of y_dish_list.bill_remark
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    public String getBillRemark() {
        return billRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_dish_list.bill_remark
     *
     * @param billRemark the value for y_dish_list.bill_remark
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    public void setBillRemark(String billRemark) {
        this.billRemark = billRemark == null ? null : billRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_dish_list.create_time
     *
     * @return the value of y_dish_list.create_time
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_dish_list.create_time
     *
     * @param createTime the value for y_dish_list.create_time
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_dish_list.dish_list_code
     *
     * @return the value of y_dish_list.dish_list_code
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    public String getDishListCode() {
        return dishListCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_dish_list.dish_list_code
     *
     * @param dishListCode the value for y_dish_list.dish_list_code
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    public void setDishListCode(String dishListCode) {
        this.dishListCode = dishListCode == null ? null : dishListCode.trim();
    }
}