package com.hht.models;

import java.util.Date;

public class YTableOprrecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_table_oprrecord.id
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_table_oprrecord.table_code
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    private String tableCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_table_oprrecord.oper_type
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    private String operType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_table_oprrecord.operator
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_table_oprrecord.oper_time
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    private Date operTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_table_oprrecord.oper_detailed
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    private String operDetailed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_table_oprrecord.id
     *
     * @return the value of y_table_oprrecord.id
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_table_oprrecord.id
     *
     * @param id the value for y_table_oprrecord.id
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_table_oprrecord.table_code
     *
     * @return the value of y_table_oprrecord.table_code
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    public String getTableCode() {
        return tableCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_table_oprrecord.table_code
     *
     * @param tableCode the value for y_table_oprrecord.table_code
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    public void setTableCode(String tableCode) {
        this.tableCode = tableCode == null ? null : tableCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_table_oprrecord.oper_type
     *
     * @return the value of y_table_oprrecord.oper_type
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    public String getOperType() {
        return operType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_table_oprrecord.oper_type
     *
     * @param operType the value for y_table_oprrecord.oper_type
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    public void setOperType(String operType) {
        this.operType = operType == null ? null : operType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_table_oprrecord.operator
     *
     * @return the value of y_table_oprrecord.operator
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_table_oprrecord.operator
     *
     * @param operator the value for y_table_oprrecord.operator
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_table_oprrecord.oper_time
     *
     * @return the value of y_table_oprrecord.oper_time
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    public Date getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_table_oprrecord.oper_time
     *
     * @param operTime the value for y_table_oprrecord.oper_time
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    public void setOperTime(Date operTime) {
        this.operTime = operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_table_oprrecord.oper_detailed
     *
     * @return the value of y_table_oprrecord.oper_detailed
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    public String getOperDetailed() {
        return operDetailed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_table_oprrecord.oper_detailed
     *
     * @param operDetailed the value for y_table_oprrecord.oper_detailed
     *
     * @mbggenerated Fri Nov 18 10:19:01 CST 2016
     */
    public void setOperDetailed(String operDetailed) {
        this.operDetailed = operDetailed == null ? null : operDetailed.trim();
    }
}